import configparser
import shutil
import subprocess

from lib.utils import constants

print(subprocess.check_output(["git", "pull"]))


config = configparser.ConfigParser()
config.read(constants.CONFIG_FILE)
ADDON_PATH = config['wow']['addon_path']


WOW_GUILDCHATLOGGER_PATH = ADDON_PATH + constants.BACK_SLASH + constants.GUILDCHATLOGGER_ADDON
SRC_GUILDCHATLOGGER_PATH = constants.ADDONS + constants.BACK_SLASH + constants.GUILDCHATLOGGER_ADDON
print('removing ' + WOW_GUILDCHATLOGGER_PATH)
shutil.rmtree(WOW_GUILDCHATLOGGER_PATH, True)
print('copying ' + SRC_GUILDCHATLOGGER_PATH + ' to ' + WOW_GUILDCHATLOGGER_PATH)
shutil.copytree(SRC_GUILDCHATLOGGER_PATH, WOW_GUILDCHATLOGGER_PATH)

WOW_OFFICERCHATLOGGER_PATH = ADDON_PATH + constants.BACK_SLASH + constants.OFFICERCHATLOGGER_ADDON
SRC_OFFICERCHATLOGGER_PATH = constants.ADDONS + constants.BACK_SLASH + constants.OFFICERCHATLOGGER_ADDON
print('removing ' + WOW_OFFICERCHATLOGGER_PATH)
shutil.rmtree(WOW_OFFICERCHATLOGGER_PATH, True)
print('copying ' + SRC_OFFICERCHATLOGGER_PATH + ' to ' + WOW_OFFICERCHATLOGGER_PATH)
shutil.copytree(SRC_OFFICERCHATLOGGER_PATH, WOW_OFFICERCHATLOGGER_PATH)

WOW_SYSTEMCHATLOGGER_PATH = ADDON_PATH + constants.BACK_SLASH + constants.SYSTEMCHATLOGGER_ADDON
SRC_SYSTEMCHATLOGGER_PATH = constants.ADDONS + constants.BACK_SLASH + constants.SYSTEMCHATLOGGER_ADDON
print('removing ' + WOW_SYSTEMCHATLOGGER_PATH)
shutil.rmtree(WOW_SYSTEMCHATLOGGER_PATH, True)
print('copying ' + SRC_SYSTEMCHATLOGGER_PATH + ' to ' + WOW_SYSTEMCHATLOGGER_PATH)
shutil.copytree(SRC_SYSTEMCHATLOGGER_PATH, WOW_SYSTEMCHATLOGGER_PATH)
